name: GitHub Actions Demo
run-name: ${{ github.actor }} - testing
on: [push]
jobs:
  basic-info:
    runs-on: ubuntu-latest
    steps:
      - name: Event Check
        run: echo "Event - ${{ github.event_name }}"
      - name: OS Check
        run: echo "OS - ${{ runner.os }}"
      - name: Repo Check
        run: echo "Repo - ${{ github.repository }}"
      - name: Branch Check
        run: echo "Branch - ${{ github.ref }}"
  repo-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Repo Content Check
        run: ls -a ${{ github.workspace }}
