name: GitHub Actions Demo
run-name: ${{ github.actor }} - testing
on: [push]
jobs:
  test-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Event check
        run: echo "Job triggered by - ${{ github.event_name }}"
      - name: OS Check
        run: echo "Running on - ${{ runner.os }}"
