name: GitHub Actions Demo
run-name: ${{ github.actor }} - testing
on: [push]
jobs:
  test-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Event Check
        run: echo "Event - ${{ github.event_name }}"
      - name: OS Check
        run: echo "OS - ${{ runner.os }}"
      - name: Repo Check
        run: echo "Repo - ${{ github.repository }}"
      - name: Branch Check
        run: echo "Branch - ${{ github.ref }}"
