name: GitHub Actions Demo
run-name: ${{ github.actor }} - testing

on: [push]

jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Event Check
        run: echo "Event - ${{ github.event_name }}"
      - name: OS Check
        run: echo "OS - ${{ runner.os }}"
      - name: Repo Check
        run: echo "Repo - ${{ github.repository }}"
      - name: Branch Check
        run: echo "Branch - ${{ github.ref_name }}"

  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Repo Content Check
        run: ls -a ${{ github.workspace }}

  detect-env:
    needs: checkout-code
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-env.outputs.env }}
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          BRANCH="${{ github.ref_name }}"
          if [[ "$BRANCH" == "master" ]]; then
            ENV="prod"
          elif [[ "$BRANCH" == "syst" ]]; then
            ENV="syst"
          else
            ENV="test"
          fi
          echo "env=$ENV" >> $GITHUB_OUTPUT

  deploy-mock:
    needs: detect-env
    runs-on: ubuntu-latest
    steps:
      - name: Mock deploy
        run: |
          echo "Deploying app '${{ github.repository }}' to environment '${{ needs.detect-env.outputs.env }}'"
